### ISSUE TITLE
Password reset - no route exists for URL supplied in email

### ISSUE THREAD

**Issue by kierancott** [develop-me/bagajob#46]
**Issue:**
The URL supplied in the email is not hitting a route.
e.g.: http://localhost:3000/password-reset/?email=nik%40nikolaso.com&token=fR7oRdqYuCgPms2N2QzSxMMCZsGX9aO8hke9l4bFGbqpbn1YIYnwn0jE5lUc
where `email=nik%40nikolaso.com` & `token=fR7oRdqYuCgPms2N2QzSxMMCZsGX9aO8hke9l4bFGbqpbn1YIYnwn0jE5lUc` are query parameters.

**Action:**
Modify the `password-reset` route in `App.js` from `/password-reset/:token` to handle both the `email` and `token` query parameters as above.

**Comment by kierancott** [comment]
# Resolved

**Action:**

- Installed `use-query-params` and `query-string` npm packages
- Wrapped all React Routes with `<QueryParamProvider ReactRouterRoute={Route}>`
- Created hooks to extract email and token from URL and dispatch with password

**Result:**

- Email and token are correctly extracted from the URL and posted to the API in format:
`{email: "email@email.com", password: "newpassword", token: "tokenstring47HFD98SJNFUIhki93"}`

<img width="1340" alt="Screenshot 2020-09-21 at 15 33 19" src="https://user-images.githubusercontent.com/52701889/93780813-847a9300-fc20-11ea-884d-bdbca81bce99.png">

**Comment by kierancott** [comment]
**Update:**

Email, Token and Password now being sent to server with status code 200.

<img width="1279" alt="Screenshot 2020-09-22 at 12 24 21" src="https://user-images.githubusercontent.com/52701889/93876543-ed204900-fcce-11ea-8431-96a29086a76f.png">
<img width="882" alt="Screenshot 2020-09-22 at 12 25 10" src="https://user-images.githubusercontent.com/52701889/93876549-eeea0c80-fcce-11ea-8cc3-2183c341874f.png">

**Comment by nosvalds** [comment]
I'm seeing this resolved in my testing!
